"""modifier post

Revision ID: 116991398def
Revises: f4d279dfe94c
Create Date: 2020-11-20 15:50:22.779132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116991398def'
down_revision = 'f4d279dfe94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author'], ['id'])
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
