"""newuser

Revision ID: 1cfed4fa2d9e
Revises: 116991398def
Create Date: 2020-11-20 15:52:17.026851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfed4fa2d9e'
down_revision = '116991398def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
