"""drop column

Revision ID: 275d9b7aca1f
Revises: 92f849d7de18
Create Date: 2020-11-21 18:47:12.393272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275d9b7aca1f'
down_revision = '92f849d7de18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profil')
    op.drop_column('user', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile', sa.VARCHAR(length=225), nullable=True))
    op.add_column('user', sa.Column('profil', sa.VARCHAR(length=225), nullable=True))
    # ### end Alembic commands ###
