"""test

Revision ID: 35bd6ad2e481
Revises: ad1576c6f77d
Create Date: 2020-11-21 19:01:49.747048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bd6ad2e481'
down_revision = 'ad1576c6f77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profil')
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=225), nullable=True))
        batch_op.add_column(sa.Column('profil', sa.VARCHAR(length=225), nullable=True))

    # ### end Alembic commands ###
