"""add new column

Revision ID: 5e8a71e156ae
Revises: 03c61247fdee
Create Date: 2020-11-20 16:38:03.197379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8a71e156ae'
down_revision = '03c61247fdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=225), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
