"""delete profil

Revision ID: 6765afd83f5d
Revises: 275d9b7aca1f
Create Date: 2020-11-21 18:50:14.785320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6765afd83f5d'
down_revision = '275d9b7aca1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profil')
    op.drop_column('user', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile', sa.VARCHAR(length=225), nullable=True))
    op.add_column('user', sa.Column('profil', sa.VARCHAR(length=225), nullable=True))
    # ### end Alembic commands ###
