"""new column

Revision ID: 92f849d7de18
Revises: 0623e724e179
Create Date: 2020-11-21 18:45:35.605523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f849d7de18'
down_revision = '0623e724e179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile', sa.VARCHAR(length=225), nullable=True))
    # ### end Alembic commands ###
