"""add new column

Revision ID: 9da17d27066b
Revises: 35bd6ad2e481
Create Date: 2020-11-21 19:11:32.749571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da17d27066b'
down_revision = '35bd6ad2e481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
