"""drop column profile

Revision ID: a65f79af3644
Revises: 9da17d27066b
Create Date: 2020-11-21 22:09:02.059178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65f79af3644'
down_revision = '9da17d27066b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=225), nullable=True))

    # ### end Alembic commands ###
