"""test

Revision ID: c0046ded0583
Revises: f90461686dd5
Create Date: 2020-11-20 16:39:24.302185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0046ded0583'
down_revision = 'f90461686dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    # ### end Alembic commands ###
